name: caddenetwork
description: A new Flutter project.

# Bu uygulama yayınlanmayacaksa 'none' bırakabilirsin.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase ve Firestore
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0

  # QR üretimi
  qr_flutter: ^4.1.0

  # QR tarama (kamera ile)
  mobile_scanner: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
